Update wrt3.yml

diff --git a/.github/workflows/wrt3.yml b/.github/workflows/wrt3.yml
--- a/.github/workflows/wrt3.yml
+++ b/.github/workflows/wrt3.yml
@@ -53,6 +53,7 @@ jobs:
           # Setup feeds
           wget https://raw.githubusercontent.com/immortalwrt/immortalwrt/v${{ matrix.build_env.tag }}/feeds.conf.default -O feeds.conf
           echo "src-git awgopenwrt https://github.com/samara15321/amneziawg-2-immortalwrt.git" >> feeds.conf
+
           if ! grep -q '^src-git packages ' feeds.conf; then
               echo "src-git packages https://github.com/immortalwrt/packages.git" >> feeds.conf
           fi
@@ -62,12 +63,14 @@ jobs:
           ./scripts/feeds install -a
 
           # Debug: показать структуру lang
-          echo "Содержимое feeds/packages/lang:"
-          ls -R feeds/packages/lang || echo "Папка lang не найдена"
+          echo "Содержимое feeds/packages/lang (для поиска golang):"
+          find feeds/packages/lang -maxdepth 3
 
           # Проверяем golang Makefile
           if [ ! -f feeds/packages/lang/golang/Makefile ]; then
-              echo "ERROR: golang Makefile not found!"
+              echo "ERROR: golang Makefile not найден по пути feeds/packages/lang/golang/Makefile"
+              echo "Проверка наличия golang в feeds/packages/lang:"
+              ls -R feeds/packages/lang | grep golang || echo "golang отсутствует"
               exit 1
           fi
 
